import "../Components.css/Navegacao.css"
import { Navegacao } from "./Navegacao";
import { Hero } from "./Hero";
import { BarraGradent } from "./BarraGradent";
import { Sobre } from "./Sobre";
import { CarrosselServicos } from "./CarrosselServicos";
import { Textos } from "../Components/Textos";
import { Duvidas } from "./Duvidas";
import { Projetos } from "./Projetos";

export function Fundo() {
    return (
        <section
            className="fundo">
            <Navegacao />
            <Hero />
            <BarraGradent />
            <Sobre />
            <div style={{ fontSize: "1px" }}>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
            </div>
            <CarrosselServicos />
            <Duvidas />
            <Projetos/>

            <div style={{ fontSize: "1px" }}>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
                <h6>.</h6>
            </div>
        </section>
    );
}